In [1]:
import pandas as pd
print("yes")

yes

In [2]:
df = pd.read_csv("./data/multimedia.txt", sep='\t')
df.describe()

,gbifID,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
count,4.922390e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1.965167e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.612677e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.846727e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.846882e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.847044e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.847199e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.542810e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.head()

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
0,1846726645,StillImage,image/jpeg,https://bugguide.net/images/cache/WRL/QAR/WRLQ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1846726650,StillImage,image/jpeg,https://bugguide.net/images/cache/1LI/ZCL/1LIZ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1846726655,StillImage,image/jpeg,https://bugguide.net/images/cache/SR3/ZIR/SR3Z...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1846726660,StillImage,image/jpeg,https://bugguide.net/images/cache/AK4/KOK/AK4K...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1846726665,StillImage,image/jpeg,https://bugguide.net/images/cache/NQZ/SBQ/NQZS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df.filter(items = ["gbifID","identifier"])

In [6]:
oc_df = pd.read_csv("./data/occurrence.txt", sep='\t')

In [7]:
oc

NameError: name 'oc' is not defined

In [13]:
for col in oc_df.columns:
    print(col)

gbifID
abstract
accessRights
accrualMethod
accrualPeriodicity
accrualPolicy
alternative
audience
available
bibliographicCitation
conformsTo
contributor
coverage
created
creator
date
dateAccepted
dateCopyrighted
dateSubmitted
description
educationLevel
extent
format
hasFormat
hasPart
hasVersion
identifier
instructionalMethod
isFormatOf
isPartOf
isReferencedBy
isReplacedBy
isRequiredBy
isVersionOf
issued
language
license
mediator
medium
modified
provenance
publisher
references
relation
replaces
requires
rights
rightsHolder
source
spatial
subject
tableOfContents
temporal
title
type
valid
institutionID
collectionID
datasetID
institutionCode
collectionCode
datasetName
ownerInstitutionCode
basisOfRecord
informationWithheld
dataGeneralizations
dynamicProperties
occurrenceID
catalogNumber
recordNumber
recordedBy
individualCount
organismQuantity
organismQuantityType
sex
lifeStage
reproductiveCondition
behavior
establishmentMeans
occurrenceStatus
preparations
disposition
associatedReferences
associatedSequences
associatedTaxa
otherCatalogNumbers
occurrenceRemarks
organismID
organismName
organismScope
associatedOccurrences
associatedOrganisms
previousIdentifications
organismRemarks
materialSampleID
eventID
parentEventID
fieldNumber
eventDate
eventTime
startDayOfYear
endDayOfYear
year
month
day
verbatimEventDate
habitat
samplingProtocol
samplingEffort
sampleSizeValue
sampleSizeUnit
fieldNotes
eventRemarks
locationID
higherGeographyID
higherGeography
continent
waterBody
islandGroup
island
countryCode
stateProvince
county
municipality
locality
verbatimLocality
verbatimElevation
verbatimDepth
minimumDistanceAboveSurfaceInMeters
maximumDistanceAboveSurfaceInMeters
locationAccordingTo
locationRemarks
decimalLatitude
decimalLongitude
coordinateUncertaintyInMeters
coordinatePrecision
pointRadiusSpatialFit
verbatimCoordinateSystem
verbatimSRS
footprintWKT
footprintSRS
footprintSpatialFit
georeferencedBy
georeferencedDate
georeferenceProtocol
georeferenceSources
georeferenceVerificationStatus
georeferenceRemarks
geologicalContextID
earliestEonOrLowestEonothem
latestEonOrHighestEonothem
earliestEraOrLowestErathem
latestEraOrHighestErathem
earliestPeriodOrLowestSystem
latestPeriodOrHighestSystem
earliestEpochOrLowestSeries
latestEpochOrHighestSeries
earliestAgeOrLowestStage
latestAgeOrHighestStage
lowestBiostratigraphicZone
highestBiostratigraphicZone
lithostratigraphicTerms
group
formation
member
bed
identificationID
identificationQualifier
typeStatus
identifiedBy
dateIdentified
identificationReferences
identificationVerificationStatus
identificationRemarks
taxonID
scientificNameID
acceptedNameUsageID
parentNameUsageID
originalNameUsageID
nameAccordingToID
namePublishedInID
taxonConceptID
scientificName
acceptedNameUsage
parentNameUsage
originalNameUsage
nameAccordingTo
namePublishedIn
namePublishedInYear
higherClassification
kingdom
phylum
class
order
family
genus
subgenus
specificEpithet
infraspecificEpithet
taxonRank
verbatimTaxonRank
vernacularName
nomenclaturalCode
taxonomicStatus
nomenclaturalStatus
taxonRemarks
datasetKey
publishingCountry
lastInterpreted
elevation
elevationAccuracy
depth
depthAccuracy
distanceAboveSurface
distanceAboveSurfaceAccuracy
issue
mediaType
hasCoordinate
hasGeospatialIssues
taxonKey
acceptedTaxonKey
kingdomKey
phylumKey
classKey
orderKey
familyKey
genusKey
subgenusKey
speciesKey
species
genericName
acceptedScientificName
verbatimScientificName
typifiedName
protocol
lastParsed
lastCrawled
repatriated
relativeOrganismQuantity
recordedByID
identifiedByID
level0Gid
level0Name
level1Gid
level1Name
level2Gid
level2Name
level3Gid
level3Name
iucnRedListCategory

In [19]:
oc_df = oc_df.filter(items=["gbifID","scientificName","vernacularName"])

In [22]:
oc_df[oc_df.vernacularName.notnull()]

,gbifID,scientificName,vernacularName
0,1846946471,"Haploa lecontei Boisduval, 1829",Leconte's Haploa
1,1846948963,"Vanessa atalanta (Linnaeus, 1758)",Red Admiral
2,1847121945,"Epipaschia superatalis Clemens, 1860",Dimorphic Macalla
3,1846757788,"Papilio cresphontes Cramer, 1777",Eastern Giant Swallowtail
8,1846727740,"Erynnis telemachus Burns, 1960",Rocky Mountain Duskywing
...,...,...,...
492234,1846966044,"Pityobius anguinus LeConte, 1853",Bipectinate Click Beetle
492235,1846741581,"Gelastocoris oculatus (Fabricius, 1798)",Big-Eyed Toad Bug
492236,1846921745,"Vanessa atalanta (Linnaeus, 1758)",Red Admiral
492237,1846937660,"Eurois occulta (Linnaeus, 1758)",Great Brocade
492238,1847094872,"Euchlaena obtusaria Hübner, 1809-1813",Obtuse Euchlaena

In [23]:
oc_df

,gbifID,scientificName,vernacularName
0,1846946471,"Haploa lecontei Boisduval, 1829",Leconte's Haploa
1,1846948963,"Vanessa atalanta (Linnaeus, 1758)",Red Admiral
2,1847121945,"Epipaschia superatalis Clemens, 1860",Dimorphic Macalla
3,1846757788,"Papilio cresphontes Cramer, 1777",Eastern Giant Swallowtail
4,1846824380,"Palpada vinetorum (Fabricius, 1799)",NaN
...,...,...,...
492234,1846966044,"Pityobius anguinus LeConte, 1853",Bipectinate Click Beetle
492235,1846741581,"Gelastocoris oculatus (Fabricius, 1798)",Big-Eyed Toad Bug
492236,1846921745,"Vanessa atalanta (Linnaeus, 1758)",Red Admiral
492237,1846937660,"Eurois occulta (Linnaeus, 1758)",Great Brocade
492238,1847094872,"Euchlaena obtusaria Hübner, 1809-1813",Obtuse Euchlaena

In [73]:
new_df = df.merge(oc_df, on="gbifID", how='left')

In [68]:
new_df = new_df[new_df.vernacularName.notnull()]

In [69]:
new_df = new_df.reset_index()

In [77]:
image_df = new_df[new_df["vernacularName"].map(new_df["vernacularName"].value_counts()) >= 100].reset_index()

In [78]:
image_df = image_df.filter(items=["gbifID","vernacularName","identifier"])

In [84]:
def replaceSpaces(name):
    return name.replace(" ", "_")

In [117]:
image_df_subset = image_df[:1000]
image_df_subset["vernacularName"] = image_df_subset["vernacularName"].apply(replaceSpaces)
image_df_subset.to_csv("image_subset.csv")

/tmp/ipykernel_4941/552627905.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  image_df_subset["vernacularName"] = image_df_subset["vernacularName"].apply(replaceSpaces)

In [114]:
import requests
import os
def download(row):
    url = row["identifier"]
    id = row["gbifID"]
    name = row["vernacularName"]
    path = f'/home/chavez/Desktop/Software/Projects/BugDiversity/ml/images/{name}'
    img_data = requests.get(url).content
    if not  os.path.exists(path):
        os.makedirs(path)
    with open(f'/home/chavez/Desktop/Software/Projects/BugDiversity/ml/images/{name}/{id}.jpg', 'wb') as handler:
        handler.write(img_data)

In [115]:
image_df_subset.apply(download, axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
995    None
996    None
997    None
998    None
999    None
Length: 1000, dtype: object